name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '27.1'
          - '26.3'
          - '25.3'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      
      - name: Install Cask
        run: |
          curl -fsSkL https://raw.github.com/cask/cask/master/go | python
          echo "$HOME/.cask/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: cask
      
      - name: Run tests
        run: |
          emacs --version
          make
